/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        passMK = new javax.swing.JPasswordField();
        chkHienMK = new javax.swing.JCheckBox();
        txtUName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btDangNhap = new javax.swing.JButton();
        anhNenLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLogin.setForeground(java.awt.Color.white);
        lblLogin.setText("LOGIN");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 130, 80));
        getContentPane().add(passMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 340, 30));

        chkHienMK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkHienMK.setForeground(java.awt.Color.white);
        chkHienMK.setText("Hiện Mật Khẩu");
        chkHienMK.addActionListener(this::chkHienMKActionPerformed);
        getContentPane().add(chkHienMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));
        getContentPane().add(txtUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 340, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Mật Khẩu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Tên Đăng Nhập");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));

        btDangNhap.setBackground(new java.awt.Color(0, 153, 0));
        btDangNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDangNhap.setForeground(java.awt.Color.white);
        btDangNhap.setText("ĐĂNG NHẬP");
        btDangNhap.addActionListener(this::btDangNhapActionPerformed);
        getContentPane().add(btDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 340, 40));

        anhNenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.png"))); // NOI18N
        getContentPane().add(anhNenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangNhapActionPerformed
       String username = txtUName.getText().trim();
    String password = new String(passMK.getPassword()); 

  
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
                "Vui lòng nhập đầy đủ Tên đăng nhập và Mật khẩu!", 
                "Cảnh báo", 
                JOptionPane.WARNING_MESSAGE);
        return;
    }


    dao.TaiKhoanDAO dao = new dao.TaiKhoanDAO();
    if (dao.checkLogin(username, password)) {
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");

       
      
        view.MainFrame main = new view.MainFrame(username);
        main.setLocationRelativeTo(null);
        main.setVisible(true);

        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, 
                "Tên đăng nhập hoặc mật khẩu không đúng!", 
                "Lỗi đăng nhập", 
                JOptionPane.ERROR_MESSAGE);
        passMK.setText("");
        passMK.requestFocus();
    }
    }//GEN-LAST:event_btDangNhapActionPerformed

    private void chkHienMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHienMKActionPerformed
       if (chkHienMK.isSelected()) {
    passMK.setEchoChar((char) 0); // Hiện mật khẩu
} else {
    passMK.setEchoChar('*');      // Che mật khẩu
}
    }//GEN-LAST:event_chkHienMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // 1. Kích hoạt giao diện FlatLaf macOS
    try {
        com.formdev.flatlaf.themes.FlatMacLightLaf.setup(); // Dùng FlatMacDarkLaf.setup() nếu là bản tối
    } catch (Exception ex) {
        System.err.println("Không thể khởi tạo giao diện FlatLaf");
    }

    // 2. Hiển thị Form Login
    java.awt.EventQueue.invokeLater(() -> {
        LoginFrame login = new LoginFrame();
        login.setLocationRelativeTo(null); // Căn giữa màn hình
        login.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhNenLogin;
    private javax.swing.JButton btDangNhap;
    private javax.swing.JCheckBox chkHienMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField passMK;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables
}
