/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import javax.swing.ImageIcon;

/**
 *
 * @author MSI
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
private String loggedInUser;

    // 2. Tạo Constructor nhận tham số username
    public MainFrame(String username) {
        this();
        this.loggedInUser = username;
        initComponents();
        
        // Căn giữa màn hình
        setLocationRelativeTo(null); 
        
        // Hiển thị tên tài khoản lên JLabel
        lblTaiKhoan.setText("ADMIN: "+this.loggedInUser);
    }
    /**
     * Creates new form MainFrame
     */
    private PanelTrangChuUI panelTrangChuUI;
    private PanelQLPhongUI panelQLPhongUI;
    private PanelNguoiThueUI panelNguoiThueUI;
    private PanelHopDongUI panelHopDongUI;
    private PanelHDvaDN panelHdDnUI;

    public MainFrame() {
        initComponents();
        //tạo tab
        TabChucNang.addTab("Trang Chủ", new PanelTrangChuUI());
        TabChucNang.addTab("Quản Lý Phòng", new PanelQLPhongUI());
        TabChucNang.addTab("Người Thuê", new PanelNguoiThueUI());
        TabChucNang.addTab("Hợp Đồng", new PanelHopDongUI());
        TabChucNang.addTab("Hóa Đơn & Điện Nước", new PanelHDvaDN());

        //icon
        TabChucNang.setIconAt(0, new ImageIcon(getClass().getResource("/icons/home.png")));
        TabChucNang.setIconAt(1, new ImageIcon(getClass().getResource("/icons/key.png")));
        TabChucNang.setIconAt(2, new ImageIcon(getClass().getResource("/icons/teamwork.png")));
        TabChucNang.setIconAt(3, new ImageIcon(getClass().getResource("/icons/contract.png")));
        TabChucNang.setIconAt(4, new ImageIcon(getClass().getResource("/icons/bill.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TabChucNang = new javax.swing.JTabbedPane();
        lblTaiKhoan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Phòng Trọ");
        setBackground(new java.awt.Color(253, 253, 253));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png")).getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("UTM Alberta Heavy", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("              QUẢN LÝ PHÒNG TRỌ");
        jLabel1.setToolTipText("");
        jLabel1.setFocusCycleRoot(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        TabChucNang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabChucNang)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Áp dụng giao diện macOS Sáng (Light Mode)
            com.formdev.flatlaf.themes.FlatMacLightLaf.setup();

            // (Tùy chọn) Bo tròn viền nút bấm & ô nhập liệu chuẩn macOS
            javax.swing.UIManager.put("Component.arc", 10);
            javax.swing.UIManager.put("Button.arc", 10);
            javax.swing.UIManager.put("TextComponent.arc", 8);

        } catch (Exception ex) {
            System.err.println("Lỗi nạp Look and Feel macOS");
        }

        /* Hiển thị Form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabChucNang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
