/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.HopDongDAO;
import dao.NguoiThueDAO;
import dao.PhongDAO;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HopDong;
import model.NguoiThue;
import model.Phong;

/**
 *
 * @author MSI
 */
public class PanelHopDongUI extends javax.swing.JPanel {

    private HopDongDAO hdDAO = new HopDongDAO();
    private PhongDAO pDAO = new PhongDAO();
    private NguoiThueDAO ntDAO = new NguoiThueDAO();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat formatter = new java.text.DecimalFormat("#,###");

    /**
     * Creates new form PanelHopDongUI
     */
    public PanelHopDongUI() {
        initComponents();
        NapComboBox();
        napDuLieuTableHopDong();
    }

    public void napDuLieuTableHopDong() {
        DefaultTableModel model = (DefaultTableModel) tblHopDong.getModel();

        String[] headers = {"Mã HĐ", "Mã Phòng", "Mã Người Thuê", "Giá Thuê", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái"};
        model.setColumnIdentifiers(headers);
        model.setRowCount(0);

        java.text.DecimalFormat formatter = new java.text.DecimalFormat("#,###");

        List<HopDong> list = hdDAO.findAll();
        for (HopDong hd : list) {
            String giaThueFormatted = formatter.format(hd.getGiaThue()).replace(",", ".") + " VNĐ";

            model.addRow(new Object[]{
                hd.getMaHD(),
                hd.getMaPhong(),
                hd.getMaNT(),
                giaThueFormatted,
                hd.getNgayBD() != null ? sdf.format(hd.getNgayBD()) : "",
                hd.getNgayKT() != null ? sdf.format(hd.getNgayKT()) : "",
                hd.getTrangThai()
            });

        }
    }

    public void NapComboBox() {
        // 1. Load danh sách Phòng vào cboChonPhong
        cboChonPhong.removeAllItems();
        PhongDAO phongDAO = new PhongDAO(); // Hoặc DAO quản lý phòng của ông
        for (Phong p : phongDAO.findAll()) {
            cboChonPhong.addItem(p.getMaPhong()); // Hoặc tên phòng tùy ý
        }

        // 2. Load danh sách Người Thuê vào CboNguoiThue
        CboNguoiThue.removeAllItems();
        NguoiThueDAO ntDAO = new NguoiThueDAO();
        for (NguoiThue nt : ntDAO.findAll()) {
            CboNguoiThue.addItem(nt.getMaNT()); // Hoặc tên người thuê
        }

        // 3. Riêng ComboBox Trạng Thái, nếu nó cố định thì add trực tiếp vào:
        cboTrangThaiPhongHD.removeAllItems();
        cboTrangThaiPhongHD.addItem("Đang hiệu lực");
        cboTrangThaiPhongHD.addItem("Đã thanh lý");
        cboTrangThaiPhongHD.addItem("Hết hạn");
    }

    public void LoadDuLieu() {
        txtHopDong.setText("");
        txtHopDong.setEnabled(true); // Mở lại khóa để nhập mã mới
        txtGiaThue.setText("");
        if (cboChonPhong.getItemCount() > 0) {
            cboChonPhong.setSelectedIndex(0);
        }
        if (CboNguoiThue.getItemCount() > 0) {
            CboNguoiThue.setSelectedIndex(0);
        }
        if (cboTrangThaiPhongHD.getItemCount() > 0) {
            cboTrangThaiPhongHD.setSelectedIndex(0);
        }
        dtcNgayBD.setDate(null);
        dtcNgayKT.setDate(null);
        tblHopDong.clearSelection(); // Bỏ chọn dòng trên bảng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHopDong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHopDong = new javax.swing.JTextField();
        txtGiaThue = new javax.swing.JTextField();
        cboChonPhong = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        dtcNgayBD = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        CboNguoiThue = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboTrangThaiPhongHD = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        dtcNgayKT = new com.toedter.calendar.JDateChooser();
        txtKeyword = new javax.swing.JTextField();
        btTimHopDong = new javax.swing.JButton();
        btThemHD = new javax.swing.JButton();
        btnGiaHan = new javax.swing.JButton();
        btThanhLyHD = new javax.swing.JButton();
        btInHD = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hợp đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.blue)); // NOI18N

        tblHopDong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHopDong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopDongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHopDong);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Hợp Đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setForeground(java.awt.Color.blue);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Hợp Đồng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Giá Thuê");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Phòng");

        txtGiaThue.setEditable(false);
        txtGiaThue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        cboChonPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChonPhong.addActionListener(this::cboChonPhongActionPerformed);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Ngày Bắt Đầu");

        dtcNgayBD.setDateFormatString("dd/MM/yyyy");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Người Thuê");

        CboNguoiThue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboNguoiThue.addActionListener(this::CboNguoiThueActionPerformed);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Trạng Thái Hợp Đồng");

        cboTrangThaiPhongHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTrangThaiPhongHD.addActionListener(this::cboTrangThaiPhongHDActionPerformed);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Ngày Kết Thúc");

        dtcNgayKT.setDateFormatString("dd/MM/yyyy");

        btTimHopDong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTimHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btTimHopDong.setText("Tìm");
        btTimHopDong.addActionListener(this::btTimHopDongActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboTrangThaiPhongHD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22)
                            .addComponent(CboNguoiThue, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dtcNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtcNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKeyword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTimHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dtcNgayBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dtcNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTimHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(CboNguoiThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(70, 70, 70))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboTrangThaiPhongHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31))))))
        );

        btThemHD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btThemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btThemHD.setText("Tạo Hợp Đồng");
        btThemHD.addActionListener(this::btThemHDActionPerformed);

        btnGiaHan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnGiaHan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contract2.png"))); // NOI18N
        btnGiaHan.setText("Gia Hạn Hợp Đồng");
        btnGiaHan.addActionListener(this::btnGiaHanActionPerformed);

        btThanhLyHD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btThanhLyHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rejected (1).png"))); // NOI18N
        btThanhLyHD.setText("Thanh Lý Hợp Đồng");
        btThanhLyHD.addActionListener(this::btThanhLyHDActionPerformed);

        btInHD.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btInHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        btInHD.setText("In Hợp Đồng");
        btInHD.addActionListener(this::btInHDActionPerformed);

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btThemHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnGiaHan)
                        .addGap(18, 18, 18)
                        .addComponent(btThanhLyHD)
                        .addGap(18, 18, 18)
                        .addComponent(btInHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btInHD, btThanhLyHD, btThemHD, btnGiaHan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiaHan)
                    .addComponent(btThanhLyHD)
                    .addComponent(btInHD)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btInHD, btThanhLyHD, btThemHD, btnGiaHan});

    }// </editor-fold>//GEN-END:initComponents

    private void btInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInHDActionPerformed

        String maHopDong = txtHopDong.getText().trim();

        if (maHopDong.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn 1 dòng Hợp Đồng từ bảng để in!",
                    "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        util.InHopDong.inHopDong(maHopDong);
    }//GEN-LAST:event_btInHDActionPerformed

    private void tblHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopDongMouseClicked
        // TODO add your handling code here:
        int row = tblHopDong.getSelectedRow();
        if (row >= 0) {
            // Lấy mã hợp đồng từ dòng được chọn ở cột 0
            String maHD = tblHopDong.getValueAt(row, 0).toString();

            // Gọi hàm findById để lấy thông tin chi tiết từ DAO
            HopDong hd = hdDAO.findById(maHD);
            if (hd != null) {
                txtHopDong.setText(hd.getMaHD());

                // Format giá thuê lên txtGiaThue dạng số nguyên gọn gàng (không bị .0)
                txtGiaThue.setText(String.format("%.0f", hd.getGiaThue()));

                // Set giá trị cho các ComboBox
                cboChonPhong.setSelectedItem(hd.getMaPhong());
                CboNguoiThue.setSelectedItem(hd.getMaNT());
                cboTrangThaiPhongHD.setSelectedItem(hd.getTrangThai());

                // Set ngày tháng cho DateChooser
                dtcNgayBD.setDate(hd.getNgayBD());
                dtcNgayKT.setDate(hd.getNgayKT());

                // Khóa mã hợp đồng lại khi đang xem/sửa
                txtHopDong.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tblHopDongMouseClicked

    private void btThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemHDActionPerformed
        if (!txtHopDong.isEnabled()) {
            txtHopDong.setText("");
            txtHopDong.setEnabled(true); // Mở khóa
            txtGiaThue.setText("");
            if (cboChonPhong.getItemCount() > 0) {
                cboChonPhong.setSelectedIndex(0);
            }
            if (CboNguoiThue.getItemCount() > 0) {
                CboNguoiThue.setSelectedIndex(0);
            }
            if (cboTrangThaiPhongHD.getItemCount() > 0) {
                cboTrangThaiPhongHD.setSelectedIndex(0);
            }
            dtcNgayBD.setDate(null);
            dtcNgayKT.setDate(null);
            tblHopDong.clearSelection();

            txtHopDong.requestFocus(); // Focus vào ô Mã HĐ
            return;
        }

        // --- NẾU Ô MÃ ĐANG MỞ THÌ TIẾN HÀNH INSERT ---
        try {
            String maHD = txtHopDong.getText().trim();
            String maPhongSelect = cboChonPhong.getSelectedItem().toString().trim();
            String maNTSelect = CboNguoiThue.getSelectedItem().toString().trim();

            if (maHD.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Mã hợp đồng không được để trống!");
                txtHopDong.requestFocus();
                return;
            }

            if (txtGiaThue.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Giá thuê không được để trống!");
                txtGiaThue.requestFocus();
                return;
            }
            double giaThue = Double.parseDouble(txtGiaThue.getText().trim());

            java.util.Date ngayBD = dtcNgayBD.getDate();
            java.util.Date ngayKT = dtcNgayKT.getDate();
            String trangThai = cboTrangThaiPhongHD.getSelectedItem().toString();

            // 1. KIỂM TRA PHÒNG ĐÃ CÓ HỢP ĐỒNG ĐANG HIỆU LỰC CHƯA
            if (hdDAO.hasActiveContract(maPhongSelect)) {
                JOptionPane.showMessageDialog(this,
                        "Phòng " + maPhongSelect + " đang có hợp đồng hiệu lực! Vui lòng thanh lý hợp đồng cũ trước.",
                        "Lỗi tạo hợp đồng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            NguoiThue nt = ntDAO.findById(maNTSelect);
            if (nt != null && nt.getMaPhong() != null && !nt.getMaPhong().trim().isEmpty()) {
               
                if (!nt.getMaPhong().trim().equalsIgnoreCase(maPhongSelect)) {
                    JOptionPane.showMessageDialog(this,
                            "Người thuê " + nt.getHoTen() + " (" + maNTSelect + ") hiện đang ở phòng " + nt.getMaPhong()
                            + "!\nKhông thể tạo hợp đồng cho phòng " + maPhongSelect + ".",
                            "Lỗi không khớp phòng", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            HopDong hd = new HopDong(maHD, maNTSelect, maPhongSelect, ngayBD, ngayKT, giaThue, trangThai);

            if (hdDAO.insert(hd)) {
                // --- BỔ SUNG CẬP NHẬT DATABASE KHI THÊM THÀNH CÔNG ---
                pDAO.updateTrangThai(maPhongSelect, "Đã thuê"); // Đổi trạng thái phòng
                ntDAO.updateMaPhong(maNTSelect, maPhongSelect); // Gán mã phòng cho người thuê

                JOptionPane.showMessageDialog(null, "Tạo hợp đồng thành công!");
                napDuLieuTableHopDong();

                // Clear dữ liệu Form
                txtHopDong.setText("");
                txtGiaThue.setText("");
                dtcNgayBD.setDate(null);
                dtcNgayKT.setDate(null);
                txtHopDong.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Tạo hợp đồng thất bại (Trùng mã hoặc lỗi CSDL)!");
                txtHopDong.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Giá thuê phải là định dạng số!");
            txtGiaThue.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btThemHDActionPerformed

    private void btnGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaHanActionPerformed
     int row = tblHopDong.getSelectedRow();
    if (row < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hợp đồng cần gia hạn trong bảng!");
        return;
    }

    try {
        String maHD = tblHopDong.getValueAt(row, 0).toString().trim();
        HopDong hdHienTai = hdDAO.findById(maHD);

        if (hdHienTai == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin hợp đồng!");
            return;
        }

        if ("Đã thanh lý".equalsIgnoreCase(hdHienTai.getTrangThai())) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Hợp đồng này ĐÃ THANH LÝ, không thể gia hạn!\nVui lòng tạo hợp đồng mới nếu khách thuê lại.",
                    "Cảnh báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maPhongMoi = cboChonPhong.getSelectedItem().toString().trim();
        String maPhongCu = hdHienTai.getMaPhong(); // Lưu lại mã phòng hiện tại
        String maNT = CboNguoiThue.getSelectedItem().toString().trim();

        if (!maPhongMoi.equalsIgnoreCase(maPhongCu)) {
            // Lấy thông tin phòng mới để kiểm tra trạng thái
            Phong phongMoi = pDAO.findById(maPhongMoi); 
            
            // Nếu phòng mới đã có người ở hoặc không ở trạng thái "Trống" -> CHẶN
            if (phongMoi != null && !"Trống".equalsIgnoreCase(phongMoi.getTrangThai())) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Phòng " + maPhongMoi + " hiện đang có hợp đồng hiệu lực (" + phongMoi.getTrangThai() + ")!\nKhông thể gia hạn chuyển sang phòng này.",
                        "Cảnh báo trùng phòng", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
      

        double giaThue = Double.parseDouble(txtGiaThue.getText().trim());

        java.util.Date ngayBD = dtcNgayBD.getDate();
        java.util.Date ngayKT = dtcNgayKT.getDate();

        if (ngayBD == null || ngayKT == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ ngày bắt đầu và ngày kết thúc!");
            return;
        }

        if (ngayKT.before(ngayBD)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ngày kết thúc mới phải sau ngày bắt đầu!");
            return;
        }

        String trangThai = "Đang hiệu lực";

        HopDong hd = new HopDong(maHD, maNT, maPhongMoi, ngayBD, ngayKT, giaThue, trangThai);

        if (hdDAO.update(hd)) {
         
            
         
            if (!maPhongMoi.equalsIgnoreCase(maPhongCu)) {
                pDAO.updateTrangThai(maPhongCu, "Trống");
            }

            pDAO.updateTrangThai(maPhongMoi, "Đã thuê");
            ntDAO.updateMaPhong(maNT, maPhongMoi);

            javax.swing.JOptionPane.showMessageDialog(this, "Gia hạn hợp đồng thành công!");

            napDuLieuTableHopDong();
            txtHopDong.setEnabled(true);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gia hạn thất bại!");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Giá thuê phải là số hợp lệ!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi gia hạn: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGiaHanActionPerformed

    private void btThanhLyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThanhLyHDActionPerformed
        int row = tblHopDong.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hợp đồng cần thanh lý trong bảng!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn thanh lý hợp đồng này không?",
                "Xác nhận thanh lý",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // 1. Lấy mã hợp đồng từ bảng
                String maHD = tblHopDong.getValueAt(row, 0).toString().trim();
                HopDong hd = hdDAO.findById(maHD);

                if (hd != null) {
                    String maPhong = hd.getMaPhong();
                    String maNguoiThue = hd.getMaNT(); // Lấy thêm MaNguoiThue từ hợp đồng

                    // 2. Cập nhật model Hợp Đồng
                    hd.setTrangThai("Đã thanh lý");

                    // 3. Lưu thay đổi hợp đồng vào CSDL
                    if (hdDAO.update(hd)) {

                        // --- BỔ SUNG & SỬA LỖI TRẢ PHÒNG ---
                        if (maPhong != null && !maPhong.isEmpty()) {
                            // Cập nhật trạng thái phòng thành 'Trống'
                            pDAO.updateTrangThai(maPhong, "Trống");
                        }

                        if (maNguoiThue != null && !maNguoiThue.isEmpty()) {

                            ntDAO.clearMaPhong(maNguoiThue);
                        }

                        // 4. Cập nhật giao diện Swing & reload lại bảng
                        cboTrangThaiPhongHD.setSelectedItem("Đã thanh lý");
                        txtHopDong.setText(hd.getMaHD());

                        napDuLieuTableHopDong();

                        JOptionPane.showMessageDialog(this, "Thanh lý hợp đồng thành công! Phòng đã được trả về trạng thái Trống.");

                    } else {
                        JOptionPane.showMessageDialog(this, "Thanh lý thất bại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy hợp đồng!");
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi thanh lý: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btThanhLyHDActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        napDuLieuTableHopDong();
        txtHopDong.setText("");
        txtGiaThue.setText("");
        dtcNgayBD.setDate(null);
        dtcNgayKT.setDate(null);

        // 2. Mở khóa ô Mã Hợp Đồng và đưa focus vào đó
        txtHopDong.setEnabled(true);
        txtHopDong.requestFocus();

        // 3. Bỏ chọn dòng trên bảng
        tblHopDong.clearSelection();

        // 4. CẬP NHẬT LẠI DANH SÁCH MỚI NHẤT CHO COMBOBOX PHÒNG
        cboChonPhong.removeAllItems();
        PhongDAO pDAO = new PhongDAO();
        for (Phong p : pDAO.findAll()) {
            cboChonPhong.addItem(p.getMaPhong());
        }

        // 5. CẬP NHẬT LẠI DANH SÁCH MỚI NHẤT CHO COMBOBOX NGƯỜI THUÊ
        CboNguoiThue.removeAllItems();
        NguoiThueDAO ntDAO = new NguoiThueDAO();
        for (NguoiThue nt : ntDAO.findAll()) {
            CboNguoiThue.addItem(nt.getMaNT());
        }

        // 6. Reset lại ComboBox Trạng Thái (nếu cần)
        cboTrangThaiPhongHD.setSelectedItem("Đang hiệu lực");
         tblHopDong.clearSelection();

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cboTrangThaiPhongHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrangThaiPhongHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTrangThaiPhongHDActionPerformed

    private void btTimHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimHopDongActionPerformed
        String keyword = txtKeyword.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tblHopDong.getModel();
        model.setRowCount(0);

        List<HopDong> list = hdDAO.findByName(keyword);
        for (HopDong hd : list) {
            String ngayBDStr = hd.getNgayBD() != null ? sdf.format(hd.getNgayBD()) : "";
            String ngayKTStr = hd.getNgayKT() != null ? sdf.format(hd.getNgayKT()) : "";
            String giaThueFormatted = formatter.format(hd.getGiaThue()).replace(",", ".") + " VNĐ";
            model.addRow(new Object[]{
                hd.getMaHD(),
                hd.getMaPhong(),
                hd.getMaNT(),
                giaThueFormatted,
                hd.getNgayBD() != null ? sdf.format(hd.getNgayBD()) : "",
                hd.getNgayKT() != null ? sdf.format(hd.getNgayKT()) : "",
                hd.getTrangThai()
            });
        }
    }//GEN-LAST:event_btTimHopDongActionPerformed

    private void cboChonPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChonPhongActionPerformed

        tinhVahienThiGiaThue();
    }//GEN-LAST:event_cboChonPhongActionPerformed

    private void CboNguoiThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboNguoiThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboNguoiThueActionPerformed
    private void tinhVahienThiGiaThue() {
        if (cboChonPhong.getSelectedItem() == null) {
            txtGiaThue.setText("0");
            return;
        }

        String rawMaPhong = cboChonPhong.getSelectedItem().toString().trim();
        String maPhong = rawMaPhong.split("-")[0].trim();

        if (!maPhong.isEmpty()) {
            Phong phong = pDAO.findById(maPhong);
            if (phong != null) {
                double giaPhong = phong.getGiaPhong();
                String loaiGia = phong.getLoaiGia();

                double tongGiaThue = giaPhong;

                if ("Theo đầu người".equalsIgnoreCase(loaiGia)) {
                    int soNguoiO = ntDAO.countNguoiThueByMaPhong(maPhong);
                    if (soNguoiO == 0) {
                        soNguoiO = 1;
                    }
                    tongGiaThue = giaPhong * soNguoiO;
                }

                txtGiaThue.setText(String.format("%.0f", tongGiaThue));
                hdDAO.updateGiaThueByMaPhong(maPhong, tongGiaThue);

            }
        }
    }

    public javax.swing.JTable getTblHopDong() {
        return tblHopDong;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboNguoiThue;
    private javax.swing.JButton btInHD;
    private javax.swing.JButton btThanhLyHD;
    private javax.swing.JButton btThemHD;
    private javax.swing.JButton btTimHopDong;
    private javax.swing.JButton btnGiaHan;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JComboBox<String> cboChonPhong;
    private javax.swing.JComboBox<String> cboTrangThaiPhongHD;
    private com.toedter.calendar.JDateChooser dtcNgayBD;
    private com.toedter.calendar.JDateChooser dtcNgayKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHopDong;
    private javax.swing.JTextField txtGiaThue;
    private javax.swing.JTextField txtHopDong;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
}
