/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.HopDongDAO;
import dao.NguoiThueDAO;
import dao.PhongDAO;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguoiThue;
import model.Phong;

/**
 *
 * @author MSI
 */
public class PanelNguoiThueUI extends javax.swing.JPanel {

    HopDongDAO hdDao = new HopDongDAO();
    NguoiThueDAO ntDAO = new NguoiThueDAO();
    PhongDAO pDAO = new PhongDAO();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form PanelNguoiThueUI
     */
    public PanelNguoiThueUI() {
        initComponents();
        NapDuLieuCboMaPhong();
        NapDuLieuTableNguoiThue();
    }

    public void NapDuLieuTableNguoiThue() {
        DefaultTableModel model = (DefaultTableModel) tblNguoiThue.getModel();

        String[] headers = {"Mã NT", "Họ Tên", "Ngày Sinh", "CCCD", "SĐT", "Email", "Ngày Vào Ở", "Mã Phòng"};
        if (model.getColumnCount() == 0 || model.getColumnName(0).equals("Title 1")) {
            model.setColumnIdentifiers(headers);
        }

        model.setRowCount(0); // Xóa dữ liệu cũ

        List<NguoiThue> list = ntDAO.findAll();
        for (NguoiThue nt : list) {
            String ngaySinhStr = nt.getNgaySinh() != null ? sdf.format(nt.getNgaySinh()) : "";
            String ngayVaoOStr = nt.getNgayVaoO() != null ? sdf.format(nt.getNgayVaoO()) : "";

            model.addRow(new Object[]{
                nt.getMaNT(),
                nt.getHoTen(),
                ngaySinhStr,
                nt.getCCCD(),
                nt.getSDT(),
                nt.getEmail(),
                ngayVaoOStr,
                nt.getMaPhong()
            });
        }
    }

    public void NapDuLieuCboMaPhong() {
        CboMaPhong.removeAllItems();
        List<Phong> dsPhong = pDAO.findAll();
        for (Phong p : dsPhong) {
            CboMaPhong.addItem(p.getMaPhong());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNguoiThue = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoCC = new javax.swing.JTextField();
        CboMaPhong = new javax.swing.JComboBox<>();
        txtKeyword = new javax.swing.JTextField();
        btTimNguoiThue = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dtcNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiThue = new javax.swing.JTable();
        btLamMoi = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btThem = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Người Thuê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setForeground(java.awt.Color.blue);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Người Thuê");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Họ Tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mã Phòng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Số Căn Cước");

        txtSoCC.addActionListener(this::txtSoCCActionPerformed);

        CboMaPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btTimNguoiThue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTimNguoiThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btTimNguoiThue.setText("Tìm");
        btTimNguoiThue.addActionListener(this::btTimNguoiThueActionPerformed);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Số điện thoại");

        txtSoDT.addActionListener(this::txtSoDTActionPerformed);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Ngày Sinh");

        dtcNgaySinh.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtNguoiThue, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addComponent(dtcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKeyword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTimNguoiThue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail)
                                .addComponent(CboMaPhong, 0, 222, Short.MAX_VALUE))
                            .addComponent(txtSoDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CboMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtNguoiThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dtcNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btTimNguoiThue)
                            .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách người thuê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.blue)); // NOI18N

        tblNguoiThue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblNguoiThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNguoiThue.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNguoiThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiThueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiThue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        btLamMoi.setText("Làm mới");
        btLamMoi.addActionListener(this::btLamMoiActionPerformed);

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(this::btXoaActionPerformed);

        btSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(this::btSuaActionPerformed);

        btThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(this::btThemActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 882, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btSua)
                        .addGap(42, 42, 42)
                        .addComponent(btXoa)
                        .addGap(45, 45, 45)
                        .addComponent(btLamMoi))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btLamMoi, btSua, btThem, btXoa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua)
                    .addComponent(btXoa)
                    .addComponent(btLamMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btLamMoi, btSua, btThem, btXoa});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSoCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoCCActionPerformed

    private void btTimNguoiThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimNguoiThueActionPerformed
        // TODO add your handling code here:
        String keyword = txtKeyword.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tblNguoiThue.getModel();
        model.setRowCount(0);

        List<NguoiThue> list = ntDAO.findByName(keyword);
        for (NguoiThue nt : list) {
            String ngaySinhStr = nt.getNgaySinh() != null ? sdf.format(nt.getNgaySinh()) : "";
            String ngayVaoOStr = nt.getNgayVaoO() != null ? sdf.format(nt.getNgayVaoO()) : "";

            model.addRow(new Object[]{
                nt.getMaNT(),
                nt.getHoTen(),
                ngaySinhStr,
                nt.getCCCD(),
                nt.getSDT(),
                nt.getEmail(),
                ngayVaoOStr,
                nt.getMaPhong()
            });
        }
    }//GEN-LAST:event_btTimNguoiThueActionPerformed

    private void tblNguoiThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiThueMouseClicked
        int row = tblNguoiThue.getSelectedRow();
        if (row >= 0) {

            Object maNTObj = tblNguoiThue.getValueAt(row, 0);
            Object hoTenObj = tblNguoiThue.getValueAt(row, 1);
            Object ngaySinhObj = tblNguoiThue.getValueAt(row, 2);
            Object soCCCObj = tblNguoiThue.getValueAt(row, 3);
            Object soDTObj = tblNguoiThue.getValueAt(row, 4);
            Object emailObj = tblNguoiThue.getValueAt(row, 5);
            Object maPhongObj = tblNguoiThue.getValueAt(row, 7);

            // Gán dữ liệu an toàn lên các ô nhập liệu
            txtNguoiThue.setText(maNTObj != null ? maNTObj.toString() : "");
            txtHoTen.setText(hoTenObj != null ? hoTenObj.toString() : "");

            // Xử lý Ngày Sinh lên JDateChooser
            if (ngaySinhObj != null) {
                try {
                    if (ngaySinhObj instanceof java.util.Date) {
                        dtcNgaySinh.setDate((java.util.Date) ngaySinhObj);
                    } else {
                        String ngaySinhStr = ngaySinhObj.toString().trim();
                        if (!ngaySinhStr.isEmpty()) {
                            dtcNgaySinh.setDate(sdf.parse(ngaySinhStr));
                        } else {
                            dtcNgaySinh.setDate(null);
                        }
                    }
                } catch (Exception e) {
                    dtcNgaySinh.setDate(null);
                }
            } else {
                dtcNgaySinh.setDate(null);
            }

            txtSoCC.setText(soCCCObj != null ? soCCCObj.toString() : "");
            txtSoDT.setText(soDTObj != null ? soDTObj.toString() : "");
            txtEmail.setText(emailObj != null ? emailObj.toString() : "");

            // Gán Mã Phòng lên ComboBox an toàn
            if (maPhongObj != null) {
                CboMaPhong.setSelectedItem(maPhongObj.toString());
            } else {
                CboMaPhong.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_tblNguoiThueMouseClicked

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed

        String cccd = txtSoCC.getText().trim();
        String sdt = txtSoDT.getText().trim();
        String ma = txtNguoiThue.getText().trim();
        String ten = txtHoTen.getText().trim();
        String email = txtEmail.getText().trim();
        String maPhong = CboMaPhong.getSelectedItem() != null ? CboMaPhong.getSelectedItem().toString().trim() : "";

        if (ma.isEmpty() || ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã và Họ tên người thuê!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.util.Date selectedDate = dtcNgaySinh.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.sql.Date ngaySql = new java.sql.Date(selectedDate.getTime());
        if (ntDAO.isCCCDExist(cccd)) {
            JOptionPane.showMessageDialog(this,
                    "Số CCCD " + cccd + " đã tồn tại trong hệ thống!",
                    "Cảnh báo trùng lặp", JOptionPane.WARNING_MESSAGE);
            txtSoCC.requestFocus();
            return;
        }
        if (ntDAO.isSDTExist(sdt)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại " + sdt + " đã được đăng ký!", "Cảnh báo trùng lặp", JOptionPane.WARNING_MESSAGE);
            txtSoDT.requestFocus();
            return;
        }
        if (cccd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số CCCD!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            txtSoCC.requestFocus();
            return;
        }
        if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            txtSoDT.requestFocus();
            return;
        }
        if (!maPhong.isEmpty()) {
            int soNguoiHienTai = ntDAO.countNguoiThueByMaPhong(maPhong);
            Phong phong = pDAO.findById(maPhong);

            if (phong == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu phòng " + maPhong + " trong CSDL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            System.out.println("DEBUG: Phong " + maPhong + " | Hien tai: " + soNguoiHienTai + " | Toi da: " + phong.getSoNguoiToiDa());

            if (soNguoiHienTai >= phong.getSoNguoiToiDa()) {
                JOptionPane.showMessageDialog(this,
                        "Phòng " + maPhong + " đã đạt số người tối đa (" + soNguoiHienTai + "/" + phong.getSoNguoiToiDa() + ")!\nKhông thể thêm người mới.",
                        "Cảnh báo phòng đã đầy", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        // ------------------------------------------------------------

        java.sql.Date ngayVaoO = new java.sql.Date(System.currentTimeMillis());

        NguoiThue nt = new NguoiThue(ma, ten, ngaySql, cccd, sdt, email, ngayVaoO, maPhong);

        if (ntDAO.insert(nt)) {

            // --- BỔ SUNG LOGIC: CẬP NHẬT TRẠNG THÁI PHÒNG THÀNH 'ĐÃ THUÊ' ---
            if (!maPhong.isEmpty()) {
                pDAO.updateTrangThai(maPhong, "Đã thuê");
            }
            // ---------------------------------------------------------------

            JOptionPane.showMessageDialog(this, "Thêm người thuê thành công!");
            NapDuLieuTableNguoiThue();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        String ma = txtNguoiThue.getText().trim();
        String ten = txtHoTen.getText().trim();
        String email = txtEmail.getText().trim();
        String maPhongMoi = CboMaPhong.getSelectedItem() != null ? CboMaPhong.getSelectedItem().toString().trim() : "";

        if (ma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn người thuê cần sửa từ bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.util.Date selectedDate = dtcNgaySinh.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.sql.Date ngaySql = new java.sql.Date(selectedDate.getTime());

        String cccd = txtSoCC.getText().trim();
        String sdt = txtSoDT.getText().trim();

        NguoiThue ntHienTai = ntDAO.findById(ma);
        if (ntHienTai == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu người thuê!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. KIỂM TRA TRÙNG CCCD
        if (!cccd.equalsIgnoreCase(ntHienTai.getCCCD())) {
            if (ntDAO.isCCCDExist(cccd)) {
                JOptionPane.showMessageDialog(this, "Số CCCD " + cccd + " đã thuộc về người thuê khác!", "Cảnh báo trùng lặp", JOptionPane.WARNING_MESSAGE);
                txtSoCC.requestFocus();
                return;
            }
        }

        // 2. KIỂM TRA TRÙNG SĐT
        if (!sdt.equalsIgnoreCase(ntHienTai.getSDT())) {
            if (ntDAO.isSDTExist(sdt)) {
                JOptionPane.showMessageDialog(this, "Số điện thoại " + sdt + " đã thuộc về người thuê khác!", "Cảnh báo trùng lặp", JOptionPane.WARNING_MESSAGE);
                txtSoDT.requestFocus();
                return;
            }
        }

        // ĐÃ SỬA: Ép về chuỗi rỗng "" nếu maPhongCu bị NULL
        String maPhongCu = (ntHienTai.getMaPhong() != null) ? ntHienTai.getMaPhong().trim() : "";

        if (!maPhongMoi.isEmpty() && !maPhongMoi.equalsIgnoreCase(maPhongCu)) {
            if (hdDao.hasActiveContractByNguoiThue(ma)) {
                JOptionPane.showMessageDialog(this,
                        "Người thuê " + ten + " đang có Hợp đồng hoạt động ở phòng " + maPhongCu + "!\nKhông thể đổi phòng trực tiếp tại đây. Vui lòng sang Tab 'Hợp Đồng' để xử lý.",
                        "Cảnh báo ràng buộc Hợp đồng", JOptionPane.WARNING_MESSAGE);
                CboMaPhong.setSelectedItem(maPhongCu.isEmpty() ? null : maPhongCu);
                return;
            }

            int soNguoiHienTaiPhongMoi = ntDAO.countNguoiThueByMaPhong(maPhongMoi);
            Phong phongMoi = pDAO.findById(maPhongMoi);

            if (phongMoi != null && soNguoiHienTaiPhongMoi >= phongMoi.getSoNguoiToiDa()) {
                JOptionPane.showMessageDialog(this,
                        "Phòng " + maPhongMoi + " đã đạt số người tối đa (" + soNguoiHienTaiPhongMoi + "/" + phongMoi.getSoNguoiToiDa() + ")!\nKhông thể chuyển người thuê sang phòng này.",
                        "Cảnh báo phòng đầy", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        // ĐÃ SỬA: Xử lý an toàn tránh NullPointerException nếu NgayVaoO chưa có
        java.sql.Date ngayVaoO = (ntHienTai.getNgayVaoO() != null)
                ? new java.sql.Date(ntHienTai.getNgayVaoO().getTime())
                : new java.sql.Date(System.currentTimeMillis());

        NguoiThue nt = new NguoiThue(ma, ten, ngaySql, cccd, sdt, email, ngayVaoO, maPhongMoi);

        if (ntDAO.update(nt)) {
            if (!maPhongMoi.equalsIgnoreCase(maPhongCu)) {
                // An toàn: maPhongCu không bao giờ bị null nữa nên gọi .isEmpty() bình thường
                if (!maPhongCu.isEmpty() && ntDAO.countNguoiThueByMaPhong(maPhongCu) == 0) {
                    pDAO.updateTrangThai(maPhongCu, "Trống");
                }
                if (!maPhongMoi.isEmpty()) {
                    pDAO.updateTrangThai(maPhongMoi, "Đã thuê");
                }
            }

            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
            NapDuLieuTableNguoiThue();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        String ma = txtNguoiThue.getText().trim();
        String ten = txtHoTen.getText().trim();
        if (ma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn người thuê cần xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Kiểm tra xem Người thuê này đã ký hợp đồng chưa
        if (ntDAO.hasHopDong(ma)) {
            JOptionPane.showMessageDialog(this,
                    "Không thể xóa! Người thuê này đang có hợp đồng tồn tại trong hệ thống.\nVui lòng thanh lý hoặc xóa hợp đồng trước.",
                    "Cảnh báo Xóa",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Nếu chưa có hợp đồng thì tiến hành hỏi và xóa như bình thường
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa người thuê " + ten + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (ntDAO.delete(ma)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                NapDuLieuTableNguoiThue();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        NapDuLieuTableNguoiThue();
        NapDuLieuCboMaPhong();

        // Clear toàn bộ các ô nhập liệu
        txtNguoiThue.setText("");
        txtHoTen.setText("");
        dtcNgaySinh.setDate(null);
        txtSoCC.setText(""); // Bổ sung dòng này để xóa Số Căn Cước
        txtSoDT.setText("");
        txtEmail.setText("");
        txtKeyword.setText("");

        // Bỏ chọn dòng trên bảng (nếu đang chọn)
        tblNguoiThue.clearSelection();

        // Đưa con trỏ chuột về lại ô Mã Người Thuê để nhập mới luôn cho lẹ
        txtNguoiThue.requestFocus();
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void txtSoDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDTActionPerformed
    public javax.swing.JTable getTblNguoiThue() {
        return tblNguoiThue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboMaPhong;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimNguoiThue;
    private javax.swing.JButton btXoa;
    private com.toedter.calendar.JDateChooser dtcNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNguoiThue;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKeyword;
    private javax.swing.JTextField txtNguoiThue;
    private javax.swing.JTextField txtSoCC;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables
}
